-- contract_risk_patterns가 2026-07-20에 마이그레이션을 거치지 않고 원격 DB에서 직접
-- 재생성되어(컬럼 구조가 category/pattern_description/risk_level/example_clause/source/keywords
-- -> pattern_name/description/severity/recommended_action로 완전히 바뀜), git 마이그레이션
-- 이력과 실제 스키마가 어긋나 있었다. 이 파일은 2026-07-21 기준 실제 원격 스키마를 그대로
-- 문서화한다 — 이후 컬럼명 혼동을 막기 위함. 기존 20건 데이터는 건드리지 않는다.
create table if not exists public.contract_risk_patterns (
  id bigint generated by default as identity primary key,
  pattern_name text not null,
  description text not null,
  severity text not null,
  recommended_action text not null,
  created_at timestamptz default now()
);

-- 보안 문제 수정: 이 테이블은 RLS가 꺼진 채로 재생성되어 anon/authenticated 키로
-- select뿐 아니라 insert/update/delete/truncate까지 가능한 상태였다(공개 anon 키로
-- 누구나 데이터를 지우거나 조작할 수 있었음). 다른 테이블들과 동일하게 RLS를 켜고
-- 읽기 전용 정책만 부여한다. 쓰기는 service_role(관리자 도구)로만 수행하므로
-- anon/authenticated의 쓰기 권한은 회수한다.
alter table public.contract_risk_patterns enable row level security;

drop policy if exists "Anyone can read risk patterns" on public.contract_risk_patterns;
create policy "Anyone can read risk patterns"
  on public.contract_risk_patterns
  for select
  to anon, authenticated
  using (true);

revoke insert, update, delete, truncate on public.contract_risk_patterns from anon, authenticated;
